In [ ]:
import numpy as np
import pandas as pd

Câu 1: Thay thế các khoảng trống bị thiếu trong một chuỗi bằng ký tự ít thường xuyên nhất.

In [15]:
# Thay thế khoảng trắng trong my_str bằng ký tự ít gặp nhất.
import numpy as np
import pandas as pd

my_str = 'dbc deb abed gade'
se = pd.Series(list(my_str))
freq = se.value_counts()
print(freq)
least_freq = freq.index[-1]
print(least_freq)
new_str = "".join(se.replace(' ', least_freq))
new_str

#freq = se.value_counts()
#print(freq)
# least_freq = ???.index[?]
# "".???(ser.replace(' ', ???))

# Gợi ý: dùng pd.Series(), value_counts(), dropna(), join()

d    4
b    3
     3
e    3
a    2
g    1
c    1
dtype: int64
c


'dbccdebcabedcgade'

--------------------
Câu 2: Lấy số hàng của giá trị lớn thứ n trong một cột.

In [5]:
import numpy as np
import pandas as pd
# Tìm vị trí hàng của giá trị lớn nhất thứ 5 của cột 'a' trong df.

df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

# Nhập code của Anh/Chị bên dưới đây:
import numpy as np
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
print(df.a)
l = list(df.a)
x = np.array(l)
y = np.sort(x, axis=-1)[::-1]
print(y)
print(y[4])
result = np.where(df.a == y[4])
result
# Gợi ý: dùng argsort()

    a   b   c
0  29  22   6
1  14  14  25
2   6   3  21
3   5  23  18
4  16  15  13
5   5   1  18
6   1  11  14
7   5   5   5
8  29  29   9
9  16  11  14
0    29
1    14
2     6
3     5
4    16
5     5
6     1
7     5
8    29
9    16
Name: a, dtype: int32
[29 29 16 16 14  6  5  5  5  1]
14


(array([1], dtype=int64),)

--------------------
Câu 3: Lấy n hàng cuối cùng của dataframe với tổng hàng > 100.

In [4]:
import numpy as np
import pandas as pd
# Lấy hai hàng cuối cùng của df mà có tổng hàng lớn hơn 100.
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Tính tổng hàng
rowsums = df.apply(np.sum, axis=1)

# Nhập code của Anh/Chị bên dưới đây:
# Trích ra hai hàng cuối có tổng > 100 từ rowsums
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
rowsums = df.apply(np.sum, axis=1)
print(rowsums)
x = np.where(rowsums > 100)
print(x)
y = np.array(x)
print(y[0][-1])
print(y[0][-2])
print(df.iloc[y[0][-1]])
print(df.iloc[y[0][-2]])
np.array(df.iloc[y[0][-1]]) 
np.array(df.iloc[y[0][-2]])

# Gợi ý: dùng .iloc[], np.where()

     0   1   2   3
0   21  32  23  15
1   37  23  14  31
2   37  15  38  21
3   33  22  24  12
4   30  11  29  28
5   11  28  39  12
6   38  31  20  26
7   34  35  25  29
8   26  24  26  35
9   26  37  23  10
10  32  25  28  37
11  34  13  18  31
12  26  36  38  32
13  18  17  16  31
14  35  14  20  37
0      91
1     105
2     111
3      91
4      98
5      90
6     115
7     123
8     111
9      96
10    122
11     96
12    132
13     82
14    106
dtype: int64
(array([ 1,  2,  6,  7,  8, 10, 12, 14], dtype=int64),)
14
12
0    35
1    14
2    20
3    37
Name: 14, dtype: int32
0    26
1    36
2    38
3    32
Name: 12, dtype: int32


array([26, 36, 38, 32])

--------------------
Câu 4: Tạo hàm (function) hoán đổi hai hàng của một dataframe.

In [3]:
# Hoán đổi hàng 1 và 2 trong df dưới đây:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

# Nhập code của Anh/Chị bên dưới đây:
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1].copy(), df.iloc[i2].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

# Gợi ý: dùng .iloc[], copy()

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


--------------------
Câu 5: Đảo ngược các hàng của một dataframe.

In [2]:
import numpy as np
import pandas as pd
# Đảo ngược tất cả các hàng của df.
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

# Nhập code của Anh/Chị bên dưới đây:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
# print(df.iloc[::-1])
# print(df.index[::1])

print(df.index[::-1])
df.reindex(index=df.index[::-1] )

# Gợi ý: có thể có nhiều cách giải

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
RangeIndex(start=4, stop=-1, step=-1)


0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4