In [46]:
# import numpy as np
import pandas as pd
my_str = 'dbc deb abed gade'
x = list(my_str)
print(x)
rrr = pd.Series(x)
rrr

index = pd.Index(x)
y = index.value_counts()
print(y)
xxx = y.index[-1]
xxx

['d', 'b', 'c', ' ', 'd', 'e', 'b', ' ', 'a', 'b', 'e', 'd', ' ', 'g', 'a', 'd', 'e']
d    4
e    3
b    3
     3
a    2
c    1
g    1
dtype: int64


'g'

In [47]:
s = pd.Series(list(my_str))
#s = pd.Index([2, 2, 5, 3, 4,1,2,4,4,6,7,np.nan])
s.value_counts()
#s.value_counts()

d    4
e    3
b    3
     3
a    2
c    1
g    1
dtype: int64

In [131]:
import numpy as np
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
print(df.a)
l = list(df.a)
x = np.array(l)
y = np.sort(x, axis=-1)[::-1]
print(y)
print(y[4])
result = np.where(df.a == y[4])
result


    a   b   c
0  23  28  28
1  22  23  12
2  16  14   7
3   7   1  28
4  16  25  20
5  28  29  15
6  17   6   4
7  18  23  14
8   1   3  16
9  24  23  21
0    23
1    22
2    16
3     7
4    16
5    28
6    17
7    18
8     1
9    24
Name: a, dtype: int32
[28 24 23 22 18 17 16 16  7  1]
18


(array([7], dtype=int64),)

In [287]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
rowsums = df.apply(np.sum, axis=1)
print(rowsums)
x = np.where(rowsums > 100)
print(x)
y = np.array(x)
print(y[0][-1])
print(y[0][-2])
print(df.iloc[y[0][-1]])
print(df.iloc[y[0][-2]])
np.array(df.iloc[y[0][-1]]) 
np.array(df.iloc[y[0][-2]])


     0   1   2   3
0   17  37  35  34
1   26  36  29  30
2   12  31  21  36
3   18  15  27  18
4   36  24  11  27
5   27  31  32  30
6   21  16  27  12
7   28  24  31  26
8   12  38  18  36
9   11  32  38  20
10  22  31  21  15
11  20  31  35  23
12  19  33  25  10
13  13  36  15  28
14  23  33  16  26
0     123
1     121
2     100
3      78
4      98
5     120
6      76
7     109
8     104
9     101
10     89
11    109
12     87
13     92
14     98
dtype: int64
(array([ 0,  1,  5,  7,  8,  9, 11], dtype=int64),)
11
9
0    20
1    31
2    35
3    23
Name: 11, dtype: int32
0    11
1    32
2    38
3    20
Name: 9, dtype: int32


array([11, 32, 38, 20])

In [289]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)

# Nhập code của Anh/Chị bên dưới đây:
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1].copy(), df.iloc[i2].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 0, 1))


    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    0   1   2   3   4
0   5   6   7   8   9
1   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


In [338]:
import pandas as pd
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
# print(df.iloc[::-1])
# print(df.index[::1])
# print(df.index[::-1])
# df.reindex(index=df.index[::-1] )
#dir(pd)
res= []
for i in reversed(df.index):
    print(i, df[i])
    res.append(df[i])
res


    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
4 0     4
1     9
2    14
3    19
4    24
Name: 4, dtype: int32
3 0     3
1     8
2    13
3    18
4    23
Name: 3, dtype: int32
2 0     2
1     7
2    12
3    17
4    22
Name: 2, dtype: int32
1 0     1
1     6
2    11
3    16
4    21
Name: 1, dtype: int32
0 0     0
1     5
2    10
3    15
4    20
Name: 0, dtype: int32


[0     4
 1     9
 2    14
 3    19
 4    24
 Name: 4, dtype: int32,
 0     3
 1     8
 2    13
 3    18
 4    23
 Name: 3, dtype: int32,
 0     2
 1     7
 2    12
 3    17
 4    22
 Name: 2, dtype: int32,
 0     1
 1     6
 2    11
 3    16
 4    21
 Name: 1, dtype: int32,
 0     0
 1     5
 2    10
 3    15
 4    20
 Name: 0, dtype: int32]